id: 67516d94baea4d07a16ed41f2890dd0f
initial_creation_type: ocr
source_metadata:
  volumes:
    6c7041a8dae64058886dc53d22e753d9:
      base_file: v092.txt
      image_group_id: I1PD95938
      title: ''
      total_pages: 1484
      volume_number: 93
